### PR TITLE
Arq 291 - Selenium extension

### PR DESCRIPTION
**Pull request by kpiwko**
Hi Aslak,

please discard all previous Selenium extension pull requests...I made one big pull request with a single commit to make your life easier, as least I hope so. If you have (partly) reviewed them, this is just a collection of cherry-picks to arquillian/arquillian master.

Could you please create a Extension - Selenium component in JIRA as well?

Thanks,
Karel

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Looks very nice. Great job!

I've added "Extension - Selenium" component to Jira..
- see source comments

**Comment by aslakknutsen** [comment]
Running only the jbossas-remote-6 profile fails. Is it possible to attach a warning in the build or something?

Running jbossas-remote-6,defaultselenium makes the 'server' window pop up twice, once pr test case. Shouldn't that be reused between testcases?

**Comment by aslakknutsen** [comment]
The integration / configuration needs docs

create doc/reference/src/main/docbook/en-US/extension_selenium.xml
add extension_selenium.xml to doc/reference/src/main/docbook/en-US/extension_reference.xml

Describe Annotations, Setup, Configuration, Dependencies etc

**Comment by kpiwko** [comment]
-Pjbossas-remote-6,defaultselenium should pop up Selenium 'Server', resp. control window really twice, because we have one Selenium instance per class paradigm. This has nothing to do with Selenium Server, which is spawned only once.

There are 3 possibilities:
1/ One Selenium per method. This way you can have really independent methods, but it is unnecessarily slow 
2/ One Selenium per class. An ideal compromise.
3/ One Selenium per whole test. This introduces problem with browser cache and can create random failure when test classes are run in a different order then previous time. It is simply not worth it, because cons are stronger than pros.

**Comment by aslakknutsen** [comment]
A ha! sounds reasonable..

**Comment by kpiwko** [comment]
Thinking about failing jbossas-remote-6 profile, I had following idea how to prevent it:

In jbossas-as-remote-6 bind surefire to 'default-test' execution with <skipTests>true</skipTest>, in other profiles bind surefire's execution to 'defaultselenium-test' etc.

This way there's no test failure when only 'jbossas-remote-6' is activated. WDYT?

**Comment by aslakknutsen** [comment]
not 100% sure what you mean, but if it works and not to much work/cripples the understanding of the pom setup..

**Comment by kpiwko** [comment]
Profiles changed, removed MavenArchetypeResolver, documentation was added. Kudos to Martin for checking documentation ;)

**Comment by aslakknutsen** [comment]
very nice docs!

**Comment by aslakknutsen** [comment]
pushed to arquillian:next

**Pull request merged**
