### PR TITLE
ARQ-124 Move jndi.properties out as configuration

### PR DESCRIPTION
**Pull request by mojavelinux**
I figured out that all we need to do is set the following three JNDI properties whenever we create an InitialContext in the container implementation:

InitialContext.INITIAL_CONTEXT_FACTORY
InitialContext.URL_PKG_PREFIXES
InitialContext.PROVIDER_URL

99% of the time, the defaults will be fine for development. The only property that really needs customizing is the last one. And that's really just a matter of setting which port the naming service is run on. So, for now, I've just abstracted out the port into configuration and use the remoteServerAddress for the host.

jndi.properties be gone!

### CODE REVIEW

**Comment by mojavelinux** [comment]
Somehow my previous pull request is getting lumped into this one. Ignore the reference documentation change (if it has already been applied).

**Comment by mojavelinux** [comment]
A compile error slipped in. Now fixed.

**Comment by aslakknutsen** [comment]
I would like to extract JNDI properties out as a 'protocol' configuration and not be a direct part of the Container configuration. e.g. https://jira.jboss.org/browse/ARQ-153

Not 100% decided on the approach tho.

**Comment by aslakknutsen** [comment]
the jndi properties fix came in via different commit

**Pull request closed without merging**
