### PR TITLE
Arq 379

### PR DESCRIPTION
**Pull request by drallen**
All the changes needed are in this request, including changing the version number in the docs for OpenEJB.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Excellent! 

Two things:
- If you could rebase against the current integration / master branch: https://github.com/arquillian/arquillian/tree/ARQ-370
- and sign a cla for Arquillian: cla.jboss.org 

i'll pull it in.

**Comment by drallen** [comment]
I was thinking about the arquillian.xml file, and that's a very good idea.  It would be great to be able to change property files per test class.  I'll take another look, or give me some hint how arquillian.xml is tied in...I just didn't see it.

I'll rebase tomorrow and push the changes again.  Working on CLA too, hadn't realized I never did it for Arquillian.

**Comment by drallen** [comment]
After rethinking the arquillian.xml configuration for OpenEJB, I'm not sure anything makes sense at the moment.  OpenEJB already has configuration, and with this fix, all those configuration options are available.
1.  For jndi.properties, it does not make sense to specify a different location, since the location is already specified by a spec for JNDI.
2.  For the OpenEJB XML configuration, it too already has at least a convention on where the file should be.  Specifying a different location via arquillian.xml just seems to be supporting non-conventional configurations that will lead to confusion.

What I was actually hoping for with arquillian.xml was a way to specify different arquillian.xml files per test, or overriding that default.  At the moment, this configuration is located exactly where the OpenEJB jndi.properties configuration should be too, and both can exist only once in a project for all tests.

For GF it was necessary, and probably still necessary for any remote containers, but for embedded OpenEJB, I can't imagine any good use cases for arquillian.xml at the moment.  Opinions?

**Comment by aslakknutsen** [comment]
One argument for having a option to specify the location in arq.xml would be you might want to configure the test suite slightly different then your production setup for what ever reason.

**Comment by drallen** [comment]
Ahh, right, good point.  I forgot there might already be such files under src/main/resources.

**Pull request closed without merging**
