### PR TITLE
Arq 394

### PR DESCRIPTION
**Pull request by drallen**
Test enricher now works with the proper services XML.  Bug can be closed after pulling this change.

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Until we add the Producers of InitialContext etc and make the Enrichers standalone, they are controlled / connected to the Container. So this SPI file should go in the OpenEJB container module, and OpenEJB needs to override the Default ResourceInjectionEnricher.lookup to provide it with the OpenEJB InitialContext.

**Comment by drallen** [comment]
Checkout these changes.  The resource injection is now done for OpenEJB using the producer (container) and injecting the context into the resource injection enricher.  There's still more cleanup for OpenEJB regarding the context stuff (prototype code that exists in OpenEJB test enricher).  This all can be better integrated in the end.

**Comment by drallen** [comment]
Do I need to generate a new pull request?  I suppose a pull request records specifically which commits to pull?

**Comment by aslakknutsen** [comment]
a pull request on a branch will show all commits the differ on that branch at all times, no need for new pull request.

**Comment by drallen** [comment]
ok, this pull request should then be ok.  Let me know if I should fix the prototype context code so that it actually gets the injected context being produced by the container now.  Since it is labeled "prototype", I'm not sure what is going to happen to it in the end.  But the EJB injections, etc. should really get resolved on the injected context, not a new IC as is currently done.

**Comment by aslakknutsen** [comment]
pushed upstream

**Comment by aslakknutsen** [comment]
pushed upstream

**Pull request closed without merging**
